"use client";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
const FORMAL_USER_ID = "e2817803-1304-4ef0-b0b8-66f473b12886";
const FORMAL_NAME = "孤星企鵝";
export function FormalAccountBinding() {
  const [mode, setMode] = useState<"hidden" | "bind" | "login">("hidden");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { let alive = true; void (async () => { if (new URLSearchParams(window.location.search).get("account") === "login") { if (alive) setMode("login"); return; } const s = await supabase.auth.getSession(); if (s.data.session?.user?.id !== FORMAL_USER_ID) return; const p = await supabase.from("profiles").select("id, anonymous_display_name").eq("id", FORMAL_USER_ID).maybeSingle(); if (alive && p.data?.anonymous_display_name === FORMAL_NAME) setMode("bind"); })(); return () => { alive = false; }; }, []);
  const close = () => { setMode("hidden"); setMessage(""); window.history.replaceState(null, "", window.location.pathname); };
  const bind = async () => { setMessage(""); if (!email.trim() || password.length < 8 || password !== confirmPassword) { setMessage("請確認 Email 與至少 8 碼的密碼，兩次密碼需一致。"); return; } setBusy(true); try { const before = await supabase.auth.getSession(); if (before.data.session?.user?.id !== FORMAL_USER_ID) throw new Error("目前匿名身分不符，已停止綁定。"); const r = await supabase.auth.updateUser({ email: email.trim(), password }); if (r.error) throw r.error; if (r.data.user?.id !== FORMAL_USER_ID) throw new Error("帳號身分驗證失敗，已停止綁定。"); const p = await supabase.from("profiles").select("id, anonymous_display_name").eq("id", FORMAL_USER_ID).maybeSingle(); if (p.error || p.data?.anonymous_display_name !== FORMAL_NAME) throw new Error("匿名資料驗證失敗，請先不要登出。"); setMessage("帳號資料已送出。若信箱收到驗證信，請完成驗證；目前匿名身分與聊天室仍保持原樣。"); } catch (e) { setMessage(e instanceof Error ? e.message : "目前無法申請帳號，請稍後再試。"); } finally { setBusy(false); } };
  const login = async () => { setMessage(""); if (!email.trim() || !password) { setMessage("請輸入 Email 與密碼。"); return; } setBusy(true); const previous = await supabase.auth.getSession(); try { const r = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (r.error) throw r.error; if (r.data.user?.id !== FORMAL_USER_ID) throw new Error("這組帳號不是此匿名身分的正式帳號。"); window.location.assign("/"); } catch (e) { const old = previous.data.session; if (old?.access_token && old?.refresh_token) await supabase.auth.setSession({ access_token: old.access_token, refresh_token: old.refresh_token }); setMessage(e instanceof Error ? e.message : "目前無法登入，請稍後再試。"); } finally { setBusy(false); } };
  if (mode === "hidden") return <a href="/?account=login" style={{position:"fixed",right:14,bottom:14,zIndex:40,fontSize:13,opacity:.82}}>已有帳號？登入</a>;
  return <div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:1000,display:"grid",placeItems:"center",background:"rgba(0,0,0,.62)",padding:18}}><section style={{width:"min(440px,100%)",background:"#17171b",color:"#fff",borderRadius:20,padding:22}}><h2>{mode === "bind" ? "申請帳號" : "登入 HerLink"}</h2><p>{mode === "bind" ? "綁定後保留目前匿名名稱、聊天室與訊息紀錄。" : "使用已綁定的帳號回到原本匿名身分。"}</p><label>電子郵件<input value={email} onChange={e=>setEmail(e.target.value)} type="email" style={{width:"100%"}} /></label><label>密碼<input value={password} onChange={e=>setPassword(e.target.value)} type="password" style={{width:"100%"}} /></label>{mode === "bind" ? <label>再次輸入密碼<input value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} type="password" style={{width:"100%"}} /></label> : null}{message?<p role="status">{message}</p>:null}<div style={{display:"flex",gap:10,marginTop:12}}><button type="button" disabled={busy} onClick={close}>取消</button><button type="button" disabled={busy} onClick={()=>void (mode === "bind" ? bind() : login())}>{busy?"處理中…":mode === "bind"?"申請帳號":"登入"}</button></div></section></div>;
}
