"use client";
import { useCallback,useEffect,useState } from "react";
import { useAdminSession } from "../../../lib/admin-client";
import { supabase } from "../../../lib/supabase";
import { AdminEmpty,AdminSection } from "../_components";
import { Button,Field,Notice } from "../../../components/ui";

type T={id:string;user_id:string;subject:string;category:string;status:string;updated_at:string;unread:boolean;deleted_at:string|null};
type M={id:string;sender_role:"user"|"admin";body:string;created_at:string;attachment_path:string|null;attachment_mime:string|null;attachment_size:number|null};
function AdminMailAttachment({path}:{path:string}){const [url,setUrl]=useState<string|null>(null);useEffect(()=>{let active=true;void supabase.storage.from("station-mail").createSignedUrl(path,3600).then((result:{data:{signedUrl:string}|null})=>{if(active)setUrl(result.data?.signedUrl??null)});return()=>{active=false}},[path]);if(!url)return <div className="muted small">照片載入中…</div>;return <a href={url} target="_blank" rel="noreferrer"><img src={url} alt="使用者照片附件" style={{display:"block",maxWidth:"min(100%,520px)",maxHeight:520,objectFit:"contain",borderRadius:14,marginTop:10}}/></a>}

export default function AdminMailbox(){
 const {session,loading}=useAdminSession();const [items,setItems]=useState<T[]>([]);const [sel,setSel]=useState<T|null>(null);const [msgs,setMsgs]=useState<M[]>([]);const [reply,setReply]=useState("");const [err,setErr]=useState<string|null>(null);const [trash,setTrash]=useState(false);const [confirmAction,setConfirmAction]=useState<{kind:"trash"|"destroy";item:T}|null>(null);
 const load=useCallback(async()=>{const {data,error}=await (supabase as any).rpc("station_mail_admin_inbox",{p_trash:trash});if(error)setErr("無法載入站長信箱。");else setItems((data??[]) as T[])},[trash]);
 useEffect(()=>{setSel(null);setMsgs([]);void load()},[trash,load]);
 useEffect(()=>{if(!session)return;void load();const c=supabase.channel("admin-mailbox-page").on("postgres_changes",{event:"*",schema:"public",table:"station_mail_threads"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"station_mail_messages"},async(payload:any)=>{void load();if(sel&&!trash){const row=(payload as any).new as {thread_id?:string};if(row?.thread_id===sel.id){const {data}=await (supabase as any).rpc("station_mail_admin_messages",{p_thread_id:sel.id});setMsgs((data??[]) as M[])}}}).subscribe();return()=>{void supabase.removeChannel(c)}},[session,load,sel,trash]);
 const open=async(t:T)=>{setSel(t);const {data,error}=await (supabase as any).rpc("station_mail_admin_messages",{p_thread_id:t.id});if(error)return setErr("無法載入信件。");setMsgs((data??[]) as M[]);if(!trash){await (supabase as any).rpc("station_mail_admin_mark_read",{p_thread_id:t.id});void load()}};
 const send=async()=>{if(!sel||trash||!reply.trim())return;const {error}=await (supabase as any).rpc("station_mail_admin_reply",{p_thread_id:sel.id,p_body:reply.trim()});if(error)return setErr("回覆失敗。");setReply("");void open(sel)};
 const moveToTrash=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_trash",{p_thread_id:t.id});if(error||data!==true)return setErr("移到垃圾桶失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([]);setReply("")}await load()};
 const restore=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_restore",{p_thread_id:t.id});if(error||data!==true)return setErr("復原失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([])}await load()};
 const destroy=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_delete",{p_thread_id:t.id});if(error||data!==true)return setErr("永久刪除失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([])}await load()};
 if(loading)return <AdminEmpty>正在載入…</AdminEmpty>;if(!session)return <AdminEmpty>請先登入管理員。</AdminEmpty>;
 return <AdminSection title="站長信箱">{err&&<Notice variant="warning">{err}</Notice>}
 <div style={{display:"flex",gap:8,marginBottom:14}}><Button variant={!trash?"primary":"secondary"} onClick={()=>setTrash(false)}>收件匣</Button><Button variant={trash?"primary":"secondary"} onClick={()=>setTrash(true)}>垃圾桶</Button></div>
 {sel?<><div style={{display:"flex",gap:8,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><Button variant="secondary" onClick={()=>setSel(null)}>返回{trash?"垃圾桶":"收件匣"}</Button><div style={{display:"flex",gap:8}}>{trash?<><Button variant="secondary" onClick={()=>void restore(sel)}>復原</Button><button type="button" onClick={()=>setConfirmAction({kind:"destroy",item:sel})} style={{padding:"10px 14px",borderRadius:10,border:"1px solid rgba(239,68,68,.5)",background:"rgba(239,68,68,.12)",color:"#fecaca",fontWeight:800,cursor:"pointer"}}>永久刪除</button></>:<button type="button" onClick={()=>setConfirmAction({kind:"trash",item:sel})} style={{padding:"10px 14px",borderRadius:10,border:"1px solid rgba(239,68,68,.35)",background:"rgba(239,68,68,.08)",color:"#fecaca",fontWeight:800,cursor:"pointer"}}>移到垃圾桶</button>}</div></div><h2>{sel.subject}</h2><div style={{display:"grid",gap:10}}>{msgs.map(m=><div key={m.id} style={{padding:12,borderRadius:12,background:m.sender_role==="admin"?"rgba(212,175,55,.14)":"rgba(255,255,255,.06)"}}><strong>{m.sender_role==="admin"?"站長":"使用者"}</strong><div>{m.body}</div>{m.attachment_path?<AdminMailAttachment path={m.attachment_path}/>:null}<small>{new Date(m.created_at).toLocaleString("zh-TW")}</small></div>)}</div>{!trash&&<><Field label="管理員回覆"><textarea className="admin-mailbox-reply" value={reply} onChange={e=>setReply(e.target.value)} maxLength={2000}/></Field><Button onClick={send}>回覆使用者</Button></>}</>:items.length===0?<AdminEmpty>{trash?"垃圾桶目前是空的。":"目前沒有信件。"}</AdminEmpty>:<div style={{display:"grid",gap:8}}>{items.map(t=><div key={t.id} style={{display:"flex",gap:8,alignItems:"stretch"}}><button onClick={()=>void open(t)} style={{padding:14,textAlign:"left",flex:1,minWidth:0}}><strong>{!trash&&t.unread?"● ":""}{t.subject}</strong><div>{trash&&t.deleted_at?`已移除 · ${new Date(t.deleted_at).toLocaleString("zh-TW")}`:`${t.status==="replied"?"已回覆":"待處理"} · ${new Date(t.updated_at).toLocaleString("zh-TW")}`}</div></button>{trash?<><button type="button" onClick={()=>void restore(t)} style={{padding:"10px 12px",borderRadius:10,alignSelf:"center",height:"fit-content",whiteSpace:"nowrap"}}>復原</button><button type="button" onClick={()=>setConfirmAction({kind:"destroy",item:t})} style={{padding:"10px 12px",borderRadius:10,color:"#fecaca",alignSelf:"center",height:"fit-content",whiteSpace:"nowrap"}}>永久刪除</button></>:<button type="button" onClick={()=>setConfirmAction({kind:"trash",item:t})} style={{padding:"10px 12px",borderRadius:10,color:"#fecaca",alignSelf:"center",height:"fit-content",whiteSpace:"nowrap"}}>垃圾桶</button>}</div>)}</div>}</AdminSection>
}