"use client";
import { useCallback,useEffect,useState } from "react";
import { useAdminSession } from "../../../lib/admin-client";
import { supabase } from "../../../lib/supabase";
import { AdminEmpty,AdminSection } from "../_components";
import { Button,Field,Notice } from "../../../components/ui";

type T={id:string;user_id:string;subject:string;category:string;status:string;updated_at:string;unread:boolean;deleted_at:string|null};
type M={id:string;sender_role:"user"|"admin";body:string;created_at:string;attachment_path:string|null;attachment_mime:string|null;attachment_size:number|null};
function AdminMailAttachment({path}:{path:string}){const [url,setUrl]=useState<string|null>(null);useEffect(()=>{let active=true;void supabase.storage.from("station-mail").createSignedUrl(path,3600).then((result:{data:{signedUrl:string}|null})=>{if(active)setUrl(result.data?.signedUrl??null)});return()=>{active=false}},[path]);if(!url)return <div className="muted small">照片載入中…</div>;return <a href={url} target="_blank" rel="noreferrer"><img src={url} alt="使用者照片附件" style={{display:"block",maxWidth:"min(100%,520px)",maxHeight:520,objectFit:"contain",borderRadius:14,marginTop:10}}/></a>}

export default function AdminMailbox(){
 const {session,loading}=useAdminSession();const [items,setItems]=useState<T[]>([]);const [sel,setSel]=useState<T|null>(null);const [msgs,setMsgs]=useState<M[]>([]);const [reply,setReply]=useState("");const [err,setErr]=useState<string|null>(null);const [trash,setTrash]=useState(false);const [confirmAction,setConfirmAction]=useState<{kind:"trash"|"destroy";item:T}|null>(null);
 const load=useCallback(async()=>{const {data,error}=await (supabase as any).rpc("station_mail_admin_inbox",{p_trash:trash});if(error)setErr("無法載入站長信箱。");else setItems((data??[]) as T[])},[trash]);
 useEffect(()=>{setSel(null);setMsgs([]);void load()},[trash,load]);
 useEffect(()=>{if(!session)return;void load();const c=supabase.channel("admin-mailbox-page").on("postgres_changes",{event:"*",schema:"public",table:"station_mail_threads"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"station_mail_messages"},async(payload:any)=>{void load();if(sel&&!trash){const row=(payload as any).new as {thread_id?:string};if(row?.thread_id===sel.id){const {data}=await (supabase as any).rpc("station_mail_admin_messages",{p_thread_id:sel.id});setMsgs((data??[]) as M[])}}}).subscribe();return()=>{void supabase.removeChannel(c)}},[session,load,sel,trash]);
 const open=async(t:T)=>{setSel(t);const {data,error}=await (supabase as any).rpc("station_mail_admin_messages",{p_thread_id:t.id});if(error)return setErr("無法載入信件。");setMsgs((data??[]) as M[]);if(!trash){await (supabase as any).rpc("station_mail_admin_mark_read",{p_thread_id:t.id});void load()}};
 const send=async()=>{if(!sel||trash||!reply.trim())return;const {error}=await (supabase as any).rpc("station_mail_admin_reply",{p_thread_id:sel.id,p_body:reply.trim()});if(error)return setErr("回覆失敗。");setReply("");void open(sel)};
 const moveToTrash=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_trash",{p_thread_id:t.id});if(error||data!==true)return setErr("移到垃圾桶失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([]);setReply("")}await load()};
 const restore=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_restore",{p_thread_id:t.id});if(error||data!==true)return setErr("復原失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([])}await load()};
 const destroy=async(t:T)=>{setErr(null);const {data,error}=await (supabase as any).rpc("station_mail_admin_delete",{p_thread_id:t.id});if(error||data!==true)return setErr("永久刪除失敗，請稍後再試。");if(sel?.id===t.id){setSel(null);setMsgs([])}await load()};
 if(loading)return <AdminEmpty>正在載入…</AdminEmpty>;if(!session)return <AdminEmpty>請先登入管理員。</AdminEmpty>;
 return <AdminSection title="站長信箱">{err&&<Notice variant="warning">{err}</Notice>}
 <div style={{display:"flex",gap:8,marginBottom:14}}><Button variant={!trash?"primary":"secondary"} onClick={()=>setTrash(false)}>收件匣</Button><Button variant={trash?"primary":"secondary"} onClick={()=>setTrash(true)}>垃圾桶</Button></div>
 {sel?<><div style={{display:"flex",gap:8,justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"}}><Button variant="secondary" onClick={()=>setSel(null)}>返回{trash?"垃圾桶":"收件匣"}</Button><div style={{display:"flex",gap:8}}>{trash?<><Button variant="secondary" onClick={()=>void restore(sel)}>復原</Button><button type="button" onClick={()=>setConfirmAction({kind:"destroy",item:sel})} style={{padding:"10px 14px",borderRadius:10,border:"1px solid rgba(239,68,68,.5)",background:"rgba(239,68,68,.12)",color:"#fecaca",fontWeight:800,cursor:"pointer"}}>永久刪除</button></>:<button type="button" onClick={()=>setConfirmAction({kind:"trash",item:sel})} style={{padding:"10px 14px",borderRadius:10,border:"1px solid rgba(239,68,68,.35)",background:"rgba(239,68,68,.08)",color:"#fecaca",fontWeight:800,cursor:"pointer"}}>移到垃圾桶</button>}</div></div><h2>{sel.subject}</h2><div style={{display:"grid",gap:10}}>{msgs.map(m=><div key={m.id} style={{padding:12,borderRadius:12,background:m.sender_role==="admin"?"rgba(212,175,55,.14)":"rgba(255,255,255,.06)"}}><strong>{m.sender_role==="admin"?"站長":"使用者"}</strong><div>{m.body}</div>{m.attachment_path?<AdminMailAttachment path={m.attachment_path}/>:null}<small>{new Date(m.created_at).toLocaleString("zh-TW")}</small></div>)}</div>{!trash&&<><Field label="管理員回覆"><textarea className="admin-mailbox-reply" value={reply} onChange={e=>setReply(e.target.value)} maxLength={2000}/></Field><Button onClick={send}>回覆使用者</Button></>}</>:items.length===0?<AdminEmpty>{trash?"垃圾桶目前是空的。":"目前沒有信件。"}</AdminEmpty>:<div style={{display:"grid",gap:10}}>{items.map(t=><article key={t.id} onClick={()=>void open(t)} style={{position:"relative",padding:"16px 52px 15px 16px",borderRadius:16,border:"1px solid rgba(255,255,255,.10)",background:t.unread&&!trash?"rgba(255,107,99,.09)":"rgba(255,255,255,.055)",cursor:"pointer",boxShadow:"0 8px 24px rgba(0,0,0,.12)"}}>
<div style={{display:"flex",alignItems:"center",gap:8,minWidth:0}}>{!trash&&t.unread?<span aria-label="未讀" style={{width:8,height:8,borderRadius:999,background:"#ff7168",flex:"0 0 auto"}}/>:null}<strong style={{fontSize:17,lineHeight:1.35,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{t.subject}</strong></div>
<div style={{marginTop:7,fontSize:13,color:"rgba(255,255,255,.58)"}}>{trash&&t.deleted_at?`已移除 · ${new Date(t.deleted_at).toLocaleString("zh-TW",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}`:`${t.status==="replied"?"已回覆":"待處理"} · ${new Date(t.updated_at).toLocaleString("zh-TW",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}`}</div>
<div onClick={e=>e.stopPropagation()} style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)"}}>{trash?<div style={{display:"flex",gap:6}}><button type="button" aria-label="復原" title="復原" onClick={()=>void restore(t)} style={{width:36,height:36,borderRadius:12,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.06)",color:"inherit",cursor:"pointer"}}>↩</button><button type="button" aria-label="永久刪除" title="永久刪除" onClick={()=>setConfirmAction({kind:"destroy",item:t})} style={{width:36,height:36,borderRadius:12,border:"1px solid rgba(239,68,68,.28)",background:"rgba(239,68,68,.08)",color:"#fecaca",cursor:"pointer"}}>×</button></div>:<button type="button" aria-label="移到垃圾桶" title="移到垃圾桶" onClick={()=>setConfirmAction({kind:"trash",item:t})} style={{width:38,height:38,borderRadius:12,border:"1px solid rgba(239,68,68,.24)",background:"rgba(239,68,68,.07)",color:"#fecaca",fontSize:18,cursor:"pointer"}}>⌫</button>}</div>
</article>)}</div>}
 {confirmAction?<div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:1000,display:"grid",placeItems:"center",padding:20,background:"rgba(0,0,0,.68)"}} onClick={()=>setConfirmAction(null)}>
  <div onClick={e=>e.stopPropagation()} style={{width:"min(100%,420px)",padding:22,borderRadius:18,border:"1px solid rgba(255,255,255,.12)",background:"#17131f",boxShadow:"0 24px 70px rgba(0,0,0,.45)"}}>
   <h3 style={{margin:"0 0 10px"}}>{confirmAction.kind==="trash"?"移到垃圾桶？":"永久刪除？"}</h3>
   <p className="muted" style={{margin:"0 0 18px",lineHeight:1.6}}>{confirmAction.kind==="trash"?"移到垃圾桶後仍可復原。":"永久刪除後無法復原，信件與附件都會刪除。"}</p>
   <div style={{display:"flex",justifyContent:"flex-end",gap:8}}>
    <Button variant="secondary" type="button" onClick={()=>setConfirmAction(null)}>取消</Button>
    <button type="button" onClick={async()=>{const action=confirmAction;setConfirmAction(null);if(action.kind==="trash")await moveToTrash(action.item);else await destroy(action.item)}} style={{padding:"10px 14px",borderRadius:10,border:"1px solid rgba(239,68,68,.5)",background:"rgba(239,68,68,.16)",color:"#fecaca",fontWeight:800,cursor:"pointer"}}>{confirmAction.kind==="trash"?"移到垃圾桶":"永久刪除"}</button>
   </div>
  </div>
 </div>:null}
 </AdminSection>
}