import { useCallback, useEffect, useMemo, useState } from "react";
import { Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useAuth } from "../../context/auth";
import { advanceRandomIcebreaker, getRandomIcebreaker, getRandomSession, leaveRandomSession, RandomMessage, RandomSession, sendRandomText } from "../../lib/random-chat";
import { supabase } from "../../lib/supabase";
import { colors } from "../../theme/colors";

export default function RandomSessionScreen() {
  const params = useLocalSearchParams<{ sessionId?: string | string[] }>(); const sessionId = useMemo(() => Array.isArray(params.sessionId) ? params.sessionId[0] : params.sessionId, [params.sessionId]);
  const { user } = useAuth(); const router = useRouter(); const [session, setSession] = useState<RandomSession | null>(null); const [messages, setMessages] = useState<RandomMessage[]>([]); const [draft, setDraft] = useState(""); const [icebreaker, setIcebreaker] = useState<any>(null);
  const load = useCallback(async () => { if (!sessionId) return; const next = await getRandomSession(sessionId); setSession(next); const { data, error } = await (supabase as any).from("random_chat_messages").select("id,session_id,content,created_at,sender_id,message_type,media_path,reply_to_message_id").eq("session_id", sessionId).order("created_at"); if (error) throw error; setMessages((data ?? []).map((item: any) => ({ ...item, is_mine: item.sender_id === user?.id }))); setIcebreaker(await getRandomIcebreaker(sessionId)); }, [sessionId, user?.id]);
  useEffect(() => { void load().catch((error) => Alert.alert("聊天載入失敗", error.message)); }, [load]);
  useEffect(() => { if (!sessionId) return; const channel = supabase.channel(`random-chat-${sessionId}`).on("postgres_changes", { event:"INSERT", schema:"public", table:"random_chat_messages", filter:`session_id=eq.${sessionId}` }, () => void load()).on("postgres_changes", { event:"UPDATE", schema:"public", table:"random_chat_sessions", filter:`id=eq.${sessionId}` }, () => void load()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [load, sessionId]);
  const send = async () => { if (!sessionId || !draft.trim() || session?.status !== "active") return; try { await sendRandomText(sessionId, draft.trim()); setDraft(""); } catch (error) { Alert.alert("送出失敗", error instanceof Error ? error.message : "請稍後再試。"); } };
  const leave = async () => { if (!sessionId) return; await leaveRandomSession(sessionId); router.replace("/random" as never); };
  return <View style={styles.root}><View style={styles.header}><Text style={styles.title}>{session?.partner_anonymous_display_name || "匿名對象"}</Text><Pressable onPress={() => void leave()}><Text style={styles.link}>離開</Text></Pressable></View>{icebreaker ? <View style={styles.ice}><Text>{icebreaker.prompt}</Text><Pressable onPress={() => void advanceRandomIcebreaker(sessionId!).then(setIcebreaker)}><Text style={styles.link}>換一題</Text></Pressable></View> : null}<FlatList style={styles.list} data={messages} keyExtractor={(item) => item.id} renderItem={({item}) => <View style={[styles.bubble,item.is_mine&&styles.mine]}><Text>{item.message_type === "image" ? "📷 圖片" : item.content}</Text></View>} /><View style={styles.composer}><TextInput style={styles.input} value={draft} onChangeText={setDraft} editable={session?.status === "active"} placeholder="輸入訊息…" /><Pressable style={styles.send} onPress={() => void send()}><Text style={styles.sendText}>送出</Text></Pressable></View></View>;
}
const styles = StyleSheet.create({root:{flex:1,backgroundColor:colors.background},header:{padding:18,flexDirection:"row",justifyContent:"space-between",backgroundColor:colors.surface},title:{fontSize:18,fontWeight:"700",color:colors.text},link:{color:colors.primary,fontWeight:"700"},ice:{margin:16,padding:14,borderRadius:12,backgroundColor:colors.surface},list:{flex:1,padding:16},bubble:{alignSelf:"flex-start",marginBottom:8,padding:12,borderRadius:14,backgroundColor:colors.surface},mine:{alignSelf:"flex-end",backgroundColor:colors.primary},composer:{flexDirection:"row",padding:12,gap:8,backgroundColor:colors.surface},input:{flex:1,backgroundColor:colors.background,padding:12,borderRadius:12,color:colors.text},send:{padding:12,justifyContent:"center",backgroundColor:colors.primary,borderRadius:12},sendText:{color:colors.primaryText,fontWeight:"700"}});
