CREATE OR REPLACE FUNCTION public.resolve_active_anonymous_chat_identity()
RETURNS UUID LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$ SELECT COALESCE((SELECT anonymous_identity_id FROM public.anonymous_identity_device_state WHERE active_auth_user_id=auth.uid() LIMIT 1),CASE WHEN EXISTS(SELECT 1 FROM public.anonymous_identity_device_state WHERE anonymous_identity_id=auth.uid()) THEN NULL ELSE auth.uid() END); $$;
REVOKE ALL ON FUNCTION public.resolve_active_anonymous_chat_identity() FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.resolve_active_anonymous_chat_identity() TO authenticated,service_role;
CREATE OR REPLACE FUNCTION public.is_active_random_session_member(p_session_id UUID,p_required_status TEXT DEFAULT NULL) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$ SELECT EXISTS(SELECT 1 FROM public.random_chat_sessions s CROSS JOIN LATERAL(SELECT public.resolve_active_anonymous_chat_identity() identity_id)a WHERE s.id=p_session_id AND a.identity_id IS NOT NULL AND(s.user_a=identity_id OR s.user_b=identity_id)AND(p_required_status IS NULL OR s.status=p_required_status)); $$;
REVOKE ALL ON FUNCTION public.is_active_random_session_member(UUID,TEXT) FROM PUBLIC,anon; GRANT EXECUTE ON FUNCTION public.is_active_random_session_member(UUID,TEXT) TO authenticated,service_role;
DROP POLICY IF EXISTS random_chat_sessions_select_own ON public.random_chat_sessions; CREATE POLICY random_chat_sessions_select_own ON public.random_chat_sessions FOR SELECT TO authenticated USING((SELECT public.resolve_active_anonymous_chat_identity())=user_a OR(SELECT public.resolve_active_anonymous_chat_identity())=user_b);
DROP POLICY IF EXISTS random_match_queue_select_own ON public.random_match_queue; CREATE POLICY random_match_queue_select_own ON public.random_match_queue FOR SELECT TO authenticated USING((SELECT public.resolve_active_anonymous_chat_identity())=user_id);
DROP POLICY IF EXISTS random_chat_messages_select_participant ON public.random_chat_messages; CREATE POLICY random_chat_messages_select_participant ON public.random_chat_messages FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.random_chat_sessions s CROSS JOIN LATERAL(SELECT public.resolve_active_anonymous_chat_identity() identity_id)a WHERE s.id=random_chat_messages.session_id AND a.identity_id IS NOT NULL AND(s.user_a=identity_id OR s.user_b=identity_id)));

CREATE OR REPLACE FUNCTION public.list_random_messages(p_session_id UUID,p_limit INTEGER DEFAULT 100) RETURNS TABLE(id UUID,session_id UUID,sender_id UUID,content TEXT,created_at TIMESTAMPTZ) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE identity_id UUID:=public.resolve_active_anonymous_chat_identity(); max_limit INTEGER:=LEAST(GREATEST(COALESCE(p_limit,100),1),200); BEGIN IF auth.uid() IS NULL OR identity_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; PERFORM public.reconcile_profile_enforcement_status(identity_id); IF NOT public.is_profile_eligible(identity_id)THEN RAISE EXCEPTION 'Your account is not available.';END IF; IF NOT public.is_active_random_session_member(p_session_id,NULL)THEN RAISE EXCEPTION 'This session is not available.';END IF; RETURN QUERY SELECT m.id,m.session_id,m.sender_id,m.content,m.created_at FROM public.random_chat_messages m WHERE m.session_id=p_session_id ORDER BY m.created_at,m.id LIMIT max_limit; END;$$;
CREATE OR REPLACE FUNCTION public.send_random_message(p_session_id UUID,p_content TEXT) RETURNS TABLE(id UUID,session_id UUID,sender_id UUID,content TEXT,created_at TIMESTAMPTZ) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE identity_id UUID:=public.resolve_active_anonymous_chat_identity(); cleaned_content TEXT:=btrim(COALESCE(p_content,'')); BEGIN IF auth.uid() IS NULL OR identity_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; IF cleaned_content='' THEN RAISE EXCEPTION 'Message cannot be blank.';END IF; IF length(cleaned_content)>2000 THEN RAISE EXCEPTION 'Message is too long.';END IF; PERFORM public.reconcile_profile_enforcement_status(identity_id); IF NOT public.is_profile_eligible(identity_id)THEN RAISE EXCEPTION 'Your account is not available.';END IF; IF NOT public.is_active_random_session_member(p_session_id,'active')THEN RAISE EXCEPTION 'This session is not available.';END IF; RETURN QUERY INSERT INTO public.random_chat_messages(session_id,sender_id,content)VALUES(p_session_id,identity_id,cleaned_content)RETURNING random_chat_messages.id,random_chat_messages.session_id,random_chat_messages.sender_id,random_chat_messages.content,random_chat_messages.created_at; END;$$;
CREATE OR REPLACE FUNCTION public.find_or_join_random_match() RETURNS TABLE(status TEXT,session_id UUID,matched_user_id UUID) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity(); BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; PERFORM pg_advisory_xact_lock(hashtextextended('herlink.random.matchmaking',0)); RETURN QUERY SELECT * FROM public.join_random_match_internal(actor_id,NULL); END;$$;
CREATE OR REPLACE FUNCTION public.leave_random_queue() RETURNS TABLE(left_queue BOOLEAN) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity(); BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; UPDATE public.random_match_queue SET status='left',updated_at=timezone('utc'::text,now()),matched_session_id=NULL WHERE user_id=actor_id AND status='waiting'; RETURN QUERY SELECT TRUE; END;$$;
CREATE OR REPLACE FUNCTION public.leave_random_session(p_session_id UUID DEFAULT NULL) RETURNS TABLE(ended BOOLEAN,session_id UUID) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity(); target_session_id UUID; target_session_status TEXT; updated_rows INTEGER:=0; BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; IF p_session_id IS NOT NULL THEN SELECT s.id,s.status INTO target_session_id,target_session_status FROM public.random_chat_sessions s WHERE s.id=p_session_id AND(s.user_a=actor_id OR s.user_b=actor_id)LIMIT 1; ELSE SELECT s.id,s.status INTO target_session_id,target_session_status FROM public.random_chat_sessions s WHERE s.status='active'AND(s.user_a=actor_id OR s.user_b=actor_id)LIMIT 1;END IF; IF target_session_id IS NULL THEN RETURN QUERY SELECT FALSE,NULL::UUID;RETURN;END IF; IF target_session_status='active'THEN UPDATE public.random_chat_sessions SET status='ended',ended_at=timezone('utc'::text,now()),ended_by=actor_id,ended_reason='left'WHERE id=target_session_id AND status='active'AND(user_a=actor_id OR user_b=actor_id);GET DIAGNOSTICS updated_rows=ROW_COUNT;IF updated_rows=0 THEN RAISE EXCEPTION 'You are not allowed to end this session.';END IF;ELSIF target_session_status<>'ended'THEN RAISE EXCEPTION 'You are not allowed to end this session.';END IF; UPDATE public.random_match_queue SET status='left',updated_at=timezone('utc'::text,now()),matched_session_id=NULL WHERE user_id=actor_id;RETURN QUERY SELECT TRUE,target_session_id; END;$$;
CREATE OR REPLACE FUNCTION public.next_random_match(p_session_id UUID) RETURNS TABLE(status TEXT,session_id UUID,matched_user_id UUID) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity();target_session RECORD;other_participant UUID; BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF;SELECT s.id,s.status,s.user_a,s.user_b INTO target_session FROM public.random_chat_sessions s WHERE s.id=p_session_id AND(s.user_a=actor_id OR s.user_b=actor_id)LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'This session is not available.';END IF;other_participant:=CASE WHEN target_session.user_a=actor_id THEN target_session.user_b ELSE target_session.user_a END;PERFORM pg_advisory_xact_lock(hashtextextended('herlink.random.matchmaking',0));IF target_session.status='active'THEN UPDATE public.random_chat_sessions SET status='ended',ended_at=timezone('utc'::text,now()),ended_by=actor_id,ended_reason='next'WHERE id=p_session_id AND status='active'AND(user_a=actor_id OR user_b=actor_id);IF NOT FOUND THEN RAISE EXCEPTION 'This session is not available.';END IF;END IF;UPDATE public.random_match_queue SET status='left',updated_at=timezone('utc'::text,now()),matched_session_id=NULL WHERE user_id=actor_id;RETURN QUERY SELECT * FROM public.join_random_match_internal(actor_id,other_participant);END;$$;

CREATE OR REPLACE FUNCTION public.block_user(target_user_id UUID) RETURNS TABLE(blocked BOOLEAN,active_match_blocked BOOLEAN) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity(); created_block_id UUID; block_count INTEGER:=0; updated_rows INTEGER:=0;
BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF; PERFORM public.assert_rate_limit('block_user',20,3600,jsonb_build_object('target_user_id',target_user_id)); IF actor_id=target_user_id THEN RAISE EXCEPTION 'You cannot block yourself.';END IF; IF NOT EXISTS(SELECT 1 FROM public.profiles WHERE id=target_user_id)THEN RAISE EXCEPTION 'Target user was not found.';END IF; INSERT INTO public.blocks(blocker_id,blocked_user_id)VALUES(actor_id,target_user_id)ON CONFLICT(blocker_id,blocked_user_id)DO NOTHING RETURNING id INTO created_block_id; DELETE FROM public.likes WHERE(from_user_id=actor_id AND to_user_id=target_user_id)OR(from_user_id=target_user_id AND to_user_id=actor_id); UPDATE public.matches SET status='blocked'WHERE status='active'AND user_1_id=LEAST(actor_id,target_user_id)AND user_2_id=GREATEST(actor_id,target_user_id);GET DIAGNOSTICS updated_rows=ROW_COUNT; SELECT COUNT(*)INTO block_count FROM public.blocks WHERE blocked_user_id=target_user_id; IF block_count=2 THEN PERFORM public.apply_risk_event(target_user_id,'multiple_blocks_received',jsonb_build_object('block_count',block_count,'triggered_by',actor_id));END IF; RETURN QUERY SELECT TRUE,updated_rows>0; END;$$;

CREATE OR REPLACE FUNCTION public.block_random_user(p_session_id UUID) RETURNS TABLE(blocked BOOLEAN,session_ended BOOLEAN) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity();target_session RECORD;target_user_id UUID;
BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF;IF p_session_id IS NULL THEN RAISE EXCEPTION 'Session is required.';END IF;SELECT s.id,s.user_a,s.user_b,s.status INTO target_session FROM public.random_chat_sessions s WHERE s.id=p_session_id AND(s.user_a=actor_id OR s.user_b=actor_id)LIMIT 1;IF NOT FOUND THEN RAISE EXCEPTION 'This session is not available.';END IF;target_user_id:=CASE WHEN target_session.user_a=actor_id THEN target_session.user_b ELSE target_session.user_a END;PERFORM public.block_user(target_user_id);UPDATE public.random_chat_sessions SET status='ended',ended_at=timezone('utc'::text,now()),ended_by=actor_id,ended_reason='blocked'WHERE id=p_session_id AND status='active'AND(user_a=actor_id OR user_b=actor_id);RETURN QUERY SELECT TRUE,FOUND;END;$$;

CREATE OR REPLACE FUNCTION public.report_random_user(p_session_id UUID,p_category TEXT,p_description TEXT DEFAULT NULL,p_block BOOLEAN DEFAULT FALSE) RETURNS TABLE(report_id UUID,status TEXT,created_at TIMESTAMPTZ,blocked BOOLEAN) LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE actor_id UUID:=public.resolve_active_anonymous_chat_identity();target_session RECORD;target_user_id UUID;normalized_description TEXT:=NULLIF(BTRIM(COALESCE(p_description,'')),'');block_result RECORD;
BEGIN IF auth.uid() IS NULL OR actor_id IS NULL THEN RAISE EXCEPTION 'Authentication required or device revoked.';END IF;IF p_session_id IS NULL THEN RAISE EXCEPTION 'Session is required.';END IF;IF NOT public.is_active_random_session_member(p_session_id,NULL)THEN RAISE EXCEPTION 'This session is not available.';END IF;IF p_category NOT IN('suspected_male_impersonation','stolen_photo','scam','money_request','investment_scam','harassment','sexual_harassment','threat','unsolicited_explicit_content','impersonation','suspected_minor','other','spam','sexual_content','fraud')THEN RAISE EXCEPTION 'Unsupported report category.';END IF;IF normalized_description IS NOT NULL AND length(normalized_description)>500 THEN RAISE EXCEPTION 'Report description is too long.';END IF;PERFORM public.check_random_action_rate_limit('report_random_user',5,INTERVAL '10 minutes',jsonb_build_object('session_id',p_session_id::TEXT,'category',p_category));SELECT s.id,s.user_a,s.user_b INTO target_session FROM public.random_chat_sessions s WHERE s.id=p_session_id AND(s.user_a=actor_id OR s.user_b=actor_id)LIMIT 1;target_user_id:=CASE WHEN target_session.user_a=actor_id THEN target_session.user_b ELSE target_session.user_a END;SELECT r.id,r.status,r.created_at INTO report_id,status,created_at FROM public.reports r WHERE r.reporter_id=actor_id AND r.reported_user_id=target_user_id AND r.category=p_category AND COALESCE(r.description,'')=COALESCE(normalized_description,'')AND r.created_at>=timezone('utc'::text,now())-INTERVAL '24 hours'ORDER BY r.created_at DESC LIMIT 1;IF FOUND THEN blocked:=FALSE;ELSE INSERT INTO public.reports(reporter_id,reported_user_id,category,description,status)VALUES(actor_id,target_user_id,p_category,normalized_description,'pending')RETURNING reports.id,reports.status,reports.created_at INTO report_id,status,created_at;blocked:=FALSE;END IF;IF p_block THEN BEGIN SELECT result.blocked,result.session_ended INTO block_result FROM public.block_random_user(p_session_id)result;blocked:=COALESCE(block_result.blocked,FALSE);EXCEPTION WHEN OTHERS THEN blocked:=FALSE;END;END IF;RETURN NEXT;END;$$;

GRANT EXECUTE ON FUNCTION public.list_random_messages(UUID,INTEGER),public.send_random_message(UUID,TEXT),public.find_or_join_random_match(),public.leave_random_queue(),public.leave_random_session(UUID),public.next_random_match(UUID),public.block_user(UUID),public.block_random_user(UUID),public.report_random_user(UUID,TEXT,TEXT,BOOLEAN) TO authenticated,service_role;
