CREATE TABLE IF NOT EXISTS public.anonymous_recovery_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code_hash TEXT NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  locked_until TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS anonymous_recovery_attempts_requester_code_time_idx
  ON public.anonymous_recovery_attempts(requester_id, code_hash, attempted_at DESC);

ALTER TABLE public.anonymous_recovery_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.anonymous_recovery_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.anonymous_recovery_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.anonymous_recovery_attempts_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.check_anonymous_recovery_rate_limit(
  p_requester_id UUID,
  p_code_hash TEXT
) RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now TIMESTAMPTZ := timezone('utc'::text, now());
  v_recent_count INTEGER := 0;
  v_locked_until TIMESTAMPTZ;
BEGIN
  IF p_requester_id IS NULL OR NULLIF(btrim(COALESCE(p_code_hash, '')), '') IS NULL THEN
    RAISE EXCEPTION 'INVALID_RECOVERY_RATE_LIMIT_INPUT';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('herlink.recovery.rate:' || p_requester_id::text || ':' || p_code_hash, 0));

  SELECT max(a.locked_until)
    INTO v_locked_until
    FROM public.anonymous_recovery_attempts a
   WHERE a.requester_id = p_requester_id
     AND a.code_hash = p_code_hash
     AND a.locked_until > v_now;

  IF v_locked_until IS NOT NULL THEN
    RAISE EXCEPTION 'RECOVERY_RATE_LIMITED';
  END IF;

  SELECT count(*)
    INTO v_recent_count
    FROM public.anonymous_recovery_attempts a
   WHERE a.requester_id = p_requester_id
     AND a.code_hash = p_code_hash
     AND a.attempted_at >= v_now - INTERVAL '15 minutes';

  IF v_recent_count >= 5 THEN
    INSERT INTO public.anonymous_recovery_attempts(requester_id, code_hash, attempted_at, locked_until)
    VALUES (p_requester_id, p_code_hash, v_now, v_now + INTERVAL '30 minutes');
    RAISE EXCEPTION 'RECOVERY_RATE_LIMITED';
  END IF;

  INSERT INTO public.anonymous_recovery_attempts(requester_id, code_hash, attempted_at)
  VALUES (p_requester_id, p_code_hash, v_now);
END;
$$;

REVOKE ALL ON FUNCTION public.check_anonymous_recovery_rate_limit(UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.check_anonymous_recovery_rate_limit(UUID, TEXT) TO service_role;
